[package]
name = "event-publisher"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing-subscriber = { version = "0.3.16", features = [ "env-filter" ] }
tokio = { version = "1.25.0"}
tracing = "0.1.37"
serde_json = "1.0.83"
events-api = { path = "../events-api" }
